//Dev URL
export const BACKEND_URL = 'http://181.215.78.135:5000/api/';
export const BACKEND_URL_MEDIA = 'http://181.215.78.135:5000/uploads/';
export const FRONT_END_URL = 'http://181.215.78.135:5000/uploads/';

//auth
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const OTP_FREEZE = 'OTP_FREEZE';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const TOKEN_CHECK = 'TOKEN_CHECK';
export const TOKEN_CHECK_FAIL = 'TOKEN_CHECK_FAIL';
export const LOGIN_ALERT_REMOVE = 'LOGIN_ALERT_REMOVE';
export const LOGOUT = 'LOGOUT';
export const RESET_SUCCESS = 'RESET_SUCCESS';
export const RESET_FAILED = 'RESET_FAILED';
export const GET_USER_DATA_BY_EMAIL = 'GET_USER_DATA_BY_EMAIL';
export const SET_LOADING_FALSE = 'SET_LOADING_FALSE';
export const SET_LOGOUT_PROVISION = 'SET_LOGOUT_PROVISION';
export const SET_LOADING_TRUE = 'SET_LOADING_TRUE';
export const RESET_LOGIN_FAILED = 'RESET_LOGIN_FAILED';
export const OTP_SETTING = 'OTP_SETTING';
export const OTP_FALSE = 'OTP_FALSE';
export const SET_DIVISION_ROLE = 'SET_DIVISION_ROLE';
export const SET_COMPANY_ROLE = 'SET_COMPANY_ROLE';
export const IDLE_TIMEOUT = 'IDLE_TIMEOUT';
export const SET_OTP_TIMEOUT = 'SET_OTP_TIMEOUT';
export const SET_CHECK_TOKEN_BOOL = 'SET_CHECK_TOKEN_BOOL';
export const RESET_IDLE_TIME = 'RESET_IDLE_TIME';
export const LIST_OF_ACTIVE_PROCESS = 'LIST_OF_ACTIVE_PROCESS';
export const SINGLE_SELF_USER = 'SINGLE_SELF_USER';

export const SET_ALERT_PROPERTY = 'SET_ALERT_PROPERTY';
export const LIST_PROPERTY_DATA = 'LIST_PROPERTY_DATA';
export const LOADING_LIST_PROPERTY = 'LOADING_LIST_PROPERTY';
export const SET_SIGNLE_PROPERTY = 'SET_SIGNLE_PROPERTY';

//User
export const SET_ALERT_USER = 'SET_ALERT_USER';
export const LIST_USER_DATA = 'LIST_USER_DATA';
export const LOADING_LIST_USER = 'LOADING_LIST_USER';
export const SET_SIGNLE_USER = 'SET_SIGNLE_USER';
